# Generated by Django 5.1.1 on 2024-09-26 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitemdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitemdetail',
            old_name='due_date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='todoitemdetail',
            name='todo_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='todo.todoitem'),
        ),
    ]
